branches:
  only:
    - gh-pages

language: python

python:
  - "3.6"

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - python scripts/fetch_all_metrics.py
  - python scripts/gen_weekly_report.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $OAUTH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: gh-pages

notifications:
  slack:
    rooms:
      - "$SLACK_TOKEN"#twitteross-metrics
