language: python

python:
  - "3.6"

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - python scripts/fetch_all_repos.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $OAUTH_TOKEN
  keep-history: true
  on:
    branch: master
  verbose: true
