branches:
  only:
    - gh-pages

language: python

python:
  - "3.6"

git:
  depth: false

install:
  - pip install -r requirements.txt

script:
  - if [ $TRAVIS_EVENT_TYPE == "cron" ];
    then ./update.sh
    else python tests.py
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $OAUTH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: gh-pages

notifications:
  slack:
    rooms:
      - "$SLACK_TOKEN"#twitteross-metrics
  email:
    recipients:
      - hmishra+travis@twitter.com
      - decause+travis@twitter.com

