name: Build site and deploy

on:
  push

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundler exec jekyll build

      - name: deploy
        uses: peaceiris/actions-gh-pages@3bdd7da #3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
