name: Build site and deploy

on:
  workflow_dispatch: {}
  schedule:
    # Run Mondays at 2:15 am
    - cron: "15 2 * * 1"

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # update stats
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: ./update.sh
        env:
          OAUTH_TOKEN: ${{ secrets.GH_API_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
      - run: |
          git config user.name 'twitter metrics'
          git config user.email 'noreply+metrics@twitter.com'
          git add -A
          git commit -m "update repo metrics data"
          git push

      # build site
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - run: bundler exec jekyll build

      - name: deploy
        uses: peaceiris/actions-gh-pages@3bdd7da #3.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
